# utils/recommender.py
# Contains all recommendation logic: scoring, filtering, and related projects.
# Kept separate from routing so it can be tested and extended independently.

import json
import os

from utils.data_loader import load_all_projects

# Maximum number of recommendations returned to the user
MAX_RESULTS = 3

# Maximum number of "you might also like" projects returned alongside results
MAX_RELATED = 3

# Scoring weights used by the recommendation engine.
# Higher weights mean that criterion has more influence
# on the final recommendation score.
SCORING_WEIGHTS = {
    "skill":    3,
    "level":    2,
    "interest": 2,
    "time":     1,
}

# Individual aliases for each weight — the test suite imports these by name.
# They point to the same values as SCORING_WEIGHTS so there is no duplication.
WEIGHT_LEVEL    = SCORING_WEIGHTS["level"]     # 2 points for a matching level
WEIGHT_INTEREST = SCORING_WEIGHTS["interest"]  # 2 points for a matching interest
WEIGHT_TIME     = SCORING_WEIGHTS["time"]       # 1 point  for matching time availability

# Common aliases and abbreviations for skills.
# This improves recommendation accuracy by normalizing user input.
SKILL_ALIASES = {
    "js":      "javascript",
    "py":      "python",
    "html5":   "html",
    "css3":    "css",
    "c++":     "cpp",
    "web dev": ["javascript", "html", "css"],
}

# Path to the precomputed cluster assignments.
# Generated by: python scripts/cluster_projects.py
_CLUSTERS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "clusters.json",
)


# ---------------------------------------------------------------------------
# Skill parsing
# ---------------------------------------------------------------------------

def parse_skills(skills_string):
    """
    Convert a skills string into a normalized lowercase list.

    Accepts two formats:
      1. JSON array (preferred): '["HTML, CSS", "JavaScript"]'
         Handles skill names that contain commas without mis-splitting.
      2. Comma-separated string (legacy fallback): "HTML, CSS, JavaScript"

    Example:    
    '["JS", "HTML5", "CSS3"]' -> ["javascript", "html", "css"]
    """
    import json

    try:
        # Preferred path: frontend sends a JSON-serialized array
        parsed = json.loads(skills_string)
        if isinstance(parsed, list):
            raw_skills = [s.strip().lower() for s in parsed if isinstance(s, str) and s.strip()]
        else:
            raise ValueError("Parsed JSON is not a list")
    except (json.JSONDecodeError, ValueError, TypeError):
        # Fallback: handle plain comma-separated strings
        raw_skills = [
            s.strip().lower()
            for s in skills_string.split(",")
            if s.strip()
        ]

    normalized_skills = []
    for skill in raw_skills:
        alias = SKILL_ALIASES.get(skill, skill)
        if isinstance(alias, list):
            normalized_skills.extend(alias)
        else:
            normalized_skills.append(alias)

    return normalized_skills


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def score_single_project(project, user_skills, level, interest, time_availability):
    """
    Calculate a numeric relevance score for one project.

    Scoring rules:
      - Each matching skill:  +3
      - Level match:          +2
      - Interest match:       +2
      - Time match:           +1

    Time filtering: projects that require MORE time than the user has
    available are excluded entirely (score returned as 0).

    Returns an integer score (0 means no match or time mismatch).
    """
    TIME_RANKS = ["low", "medium", "high"]

    user_time    = time_availability.strip().lower()
    project_time = project.get("time", "").strip().lower()

    # If the project needs more time than the user has, exclude it.
    if project_time not in TIME_RANKS or user_time not in TIME_RANKS:
        return 0
    if TIME_RANKS.index(project_time) > TIME_RANKS.index(user_time):
        return 0

    score = 0

    # Compare user's skills against the project's required skills
    project_skills = []
    for s in project.get("skills", []):
        alias = SKILL_ALIASES.get(s.lower(), s.lower())
        if isinstance(alias, list):
            project_skills.extend(alias)
        else:
            project_skills.append(alias)

    matched_skills = sum(1 for skill in user_skills if skill in project_skills)
    total_project_skills = len(project_skills)
    coverage_ratio = matched_skills / total_project_skills if total_project_skills > 0 else 0.0

    score += matched_skills * SCORING_WEIGHTS["skill"] * coverage_ratio

    if project.get("level", "").lower() == level.lower():
        score += SCORING_WEIGHTS["level"]

    if project.get("interest", "").lower() == interest.lower():
        score += SCORING_WEIGHTS["interest"]

    if project_time == user_time:
        score += SCORING_WEIGHTS["time"]

    return score


# ---------------------------------------------------------------------------
# Clustering helpers
# ---------------------------------------------------------------------------

def _load_clusters():
    """
    Load clusters.json if it exists.

    Returns the parsed dict, or None if the file is missing or unreadable.
    A missing file is a soft failure — the recommender still works,
    it just won't return related projects.
    """
    if not os.path.exists(_CLUSTERS_PATH):
        return None
    try:
        with open(_CLUSTERS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def _get_related(recommended_ids, all_projects, cluster_data):
    """
    Find projects in the same cluster(s) as the recommended projects,
    excluding the ones already recommended.

    Returns up to MAX_RELATED project dicts.
    """
    clusters = cluster_data.get("clusters", {})  # {str(pid): cid}
    members  = cluster_data.get("members",  {})  # {str(cid): [pid, ...]}

    # Collect which clusters the recommended projects belong to.
    relevant_cluster_ids = set()
    for pid in recommended_ids:
        cid = clusters.get(str(pid))
        if cid is not None:
            relevant_cluster_ids.add(str(cid))

    if not relevant_cluster_ids:
        return []

    # Gather candidate IDs from those clusters, excluding already recommended.
    candidate_ids = []
    for cid in relevant_cluster_ids:
        for pid in members.get(cid, []):
            if pid not in recommended_ids and pid not in candidate_ids:
                candidate_ids.append(pid)

    id_to_project = {p["id"]: p for p in all_projects}
    related = [id_to_project[pid] for pid in candidate_ids if pid in id_to_project]
    return related[:MAX_RELATED]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_recommendations(skills_string, level, interest, time_availability):
    """
    Return the top N recommended projects for the given user inputs,
    along with related projects from the same cluster.

    Return shape:
        {
            "recommendations": [ <project>, ... ],  # up to MAX_RESULTS
            "related":         [ <project>, ... ],  # up to MAX_RELATED
        }

    The "related" list is empty when clusters.json does not exist yet.
    Run scripts/cluster_projects.py to generate it.
    """
    user_skills  = parse_skills(skills_string)
    all_projects = load_all_projects()

    scored = []
    for project in all_projects:
        score = score_single_project(
            project, user_skills, level, interest, time_availability
        )
        if score >= SCORING_WEIGHTS["skill"]:
            scored.append({"project": project, "score": score})

    scored.sort(key=lambda item: item["score"], reverse=True)
    top_projects = [item["project"] for item in scored[:MAX_RESULTS]]
    top_ids      = [p["id"] for p in top_projects]

    # -----------------------------------------------------------------------
    # CHANGE: Attach match_score (0–10) to each recommended project
    # REASON: The issue required showing a score out of 10 on each project card.
    #         We loop over the top scored items, normalize each raw score to a
    #         0–10 scale, and attach it as "match_score" on a copy of the project.
    # NOTE:   The remote added "related" projects — we keep that too and add
    #         match_score only to the "recommendations" list, not "related".
    # -----------------------------------------------------------------------

    recommendations = []  # will hold the top projects with match_score attached

    for item in scored[:MAX_RESULTS]:
        project   = item["project"]  # the full project dict (title, skills, level, etc.)
        raw_score = item["score"]    # raw float score from score_single_project()

        # Calculate the maximum possible score for this project to normalize to 0–10
        num_skills = len(project.get("skills", []))  # how many skills this project needs
        max_score = (
            (num_skills * SCORING_WEIGHTS["skill"])  # best possible skill contribution
            + SCORING_WEIGHTS["level"]               # +2 if level matches
            + SCORING_WEIGHTS["interest"]            # +2 if interest matches
            + SCORING_WEIGHTS["time"]                # +1 if time matches
        )

        # Normalize: (raw ÷ max) × 10, rounded to 1 decimal  e.g. 7.5
        if max_score > 0:
            match_score = round((raw_score / max_score) * 10, 1)
        else:
            match_score = 0.0  # safety fallback

        # Use a shallow copy so we never mutate the shared in-memory cache
        project_with_score = dict(project)               # copy, not the original
        project_with_score["match_score"] = match_score  # attach the 0–10 score

        recommendations.append(project_with_score)

    top_ids = [p["id"] for p in recommendations]  # used by _get_related() below

    # Remote feature: find projects in the same cluster as recommended ones
    cluster_data = _load_clusters()
    related = _get_related(top_ids, all_projects, cluster_data) if cluster_data else []

    return {
        "recommendations": recommendations,  # each project includes "match_score"
        "related":         related,           # related projects (no score — not a match result)
    }


VALID_LEVELS            = ["beginner", "intermediate", "advanced"]
VALID_TIME_AVAILABILITY = ["low", "medium", "high"]
# VALID_INTERESTS: interests that exist in the project dataset (from data/projects.json)
VALID_INTERESTS = ["web", "data", "automation", "backend", "cybersecurity",
                   "education", "games"]  # compared lowercase against user input


def validate_recommendation_inputs(skills, level, interest, time_availability):
    errors = []

    if not skills or not skills.strip():
        errors.append("Please enter at least one skill.")
    elif not parse_skills(skills):
        errors.append("Please enter at least one valid skill.")

    if not level or not level.strip():
        errors.append("Please select an experience level.")
    elif level.strip().lower() not in VALID_LEVELS:
        errors.append("Invalid experience level. Choose Beginner, Intermediate, or Advanced.")

    if not interest or not isinstance(interest, str) or interest.strip().lower() not in VALID_INTERESTS:
        errors.append("Please select a valid area of interest.")

    if not time_availability or not time_availability.strip():
        errors.append("Please select your time availability.")
    elif time_availability.strip().lower() not in VALID_TIME_AVAILABILITY:
        errors.append("Invalid time availability. Choose Low, Medium, or High.")

    return errors